name: YAF.Website (.NET v8)
on:
  push:
    branches:
      - main
      
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '9.0.x' ]

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies
        working-directory: ./
        run: dotnet restore ./YAF.Website.slnx
      - name: Build
        working-directory: ./
        run: dotnet build ./YAF.Website.slnx